url = 'https://vantxqa.livmor.com/userLogin'
browser = 'chrome'
LOGIN_PATIENT_USERNAME_VALID = 'dominicbose'
LOGIN_PATIENT_USERNAME_INVALID = 'domini'
LOGIN_PATIENT_PASSWORD_VALID = 'Health@10'
LOGIN_PATIENT_PASSWORD_INVALID = 'Health@'
LOGIN_PATIENT_SUCCESS_URL = 'https://vantxqa.livmor.com/secured/showPatientDashboard?unm=UOqumux%2FwRKI3ISJfT7uWQ%3D%3D&utp=kfyD8SthKWWmumZqBJG4Gg%3D%3D&ugen=S8uCswRJkMZj2D2sueyhMg%3D%3D&hppg=81Lw1a0FSJuVOXHyTW3YvQ%3D%3D'
LOGIN_ERROR_MESSAGE_LOCATOR = '//p[@class="errorMessage"]'
LOGIN_ERROR_MESSAGE = 'Invalid Username or Password.'
LOGIN_ERROR_URL = 'https://vantxqa.livmor.com/userLoginError?error=1'
LOGIN_ERROR_BLANK_USERNAME_LOCATOR = '//p[@class="usernameTip"]'
LOGIN_ERROR_BLANK_USERNAME = 'Username required'
LOGIN_ERROR_BLANK_PASSWORD_LOCATOR = '//p[@class="passwordTip"]'
LOGIN_ERROR_BLANK_PASSWORD = 'Password required'
LOGIN_PAGE_TITLE = 'LIVMOR'
LOGIN_PAGE_CONTACT_US_LINK = '//a[@href="https://www.livmor.com/techsupportcontact"]'
LOGIN_PAGE_PRIVACY = '//span[@data-target="#privacyModal"]'
LOGIN_PAGE_TNC = '//span[@data-target="#termsModal"]'
LOGIN_PAGE_LIVMOR_LOGO = '//img[@class="inversLogo"]'
LOGIN_PAGE_USERNAME_FIELD = '//input[@id="userId"]'
LOGIN_PAGE_USERNAME_FIELD_PLACEHOLDER = 'Patient ID / Physician Email Address'
LOGIN_PAGE_PASSWORD_FIELD = '//input[@id="password"]'
LOGIN_PAGE_PASSWORD_FIELD_TYPE = 'password'
LOGIN_PAGE_PASSWORD_FIELD_TYPE_CLICKED_SHOW = 'text'
LOGIN_PAGE_PASSWORD_FIELD_PLACEHOLDER = 'Password'
LOGIN_PAGE_SHOW_PASSWORD = '//input[@type="checkbox"]'
LOGIN_PAGE_LOGIN_BUTTON = '//button[@id="btn_login"]'

# Sorting Variables
SORT_COLUMN_LOCATOR_COMMON = '//*[@id="PatientList"]/tbody/tr['
SORT_COLUMN_LOCATOR_LAST_NAME = ']/td[1]/div'
SORT_COLUMN_LOCATOR_FIRST_NAME = ']/td[2]/div'
SORT_COLUMN_LOCATOR_CONTACT = ']/td[4]/div'
SORT_COLUMN_LOCATOR_PATIENT_ID = ']/td[5]/div'
SORT_COLUMN_LOCATOR_DEPARTMENT = ']/td[6]/div'


